----------------------------------------------------------------------------------------------------------------------------------------
Lecture 1: SPRING SECURITY
----------------------------------------------------------------------------------------------------------------------------------------

1. Authentication:
    - Validates username/password or token

2. Authorization:
    - Checks roles/authorities after authentication

----------------------------------------------------------------------------------------------------------------------------------------

Spring Security Overview:

1. Adding the Spring Security dependency automatically secures all controller APIs.
2. If no username/password is configured, Spring Security generates a random password (UUID) at application startup.
3. When any API is accessed, Spring Security redirects the user to the login page.
4. After successful login, the user is redirected back to the originally requested API.
5. Sessions are stored server-side. Once authenticated through any API, the user can access all other endpoints without re-logging in until the session expires.

----------------------------------------------------------------------------------------------------------------------------------------

Session:
- When a user login the application for the first time, the server creates a session with user details.
- The session ends when it expires (default: 30 minutes) or when the user logs out.

JSESSIONID:
- A unique session ID generated by the server.
- Sent to the client as a cookie
- On later requests, the browser sends back the JSESSIONID so the server can identify the user session.

----------------------------------------------------------------------------------------------------------------------------------------

Spring Security Filter Chain:

- A chain of security filters applied to every HTTP request
- Placed between the DispatcherServlet and the Controller.

Key Components:

1. UsernamePasswordAuthenticationFilter:
    → Intercepts login requests         → extracts username and password
    → creates an authentication token   → Sends the token to the AuthenticationManager

2. AuthenticationManager:
    → Accepts the authentication token  → Delegates credential to AuthenticationProvider

3. AuthenticationProvider:
    → Performs actual credential validation.
    → Calls UserDetailsService to load user data.
    → Compares the password 
    → Returns a fully authenticated Authentication object containing user details and authorities.

4. Authentication Object:
    → Contains Principal(UserDetails), Credentials (usually null after auth), Roles.

5. UserDetailsService:
    → Loads user data from DB
    → Returns a UserDetails object

6. UserDetails:
    → Represents authenticated user information
    → Contains username, password, authorities, account status

----------------------------------------------------------------------------------------------------------------------------------------

Authentication Flow:
→ User submits login form.
→ UsernamePasswordAuthenticationFilter extracts credentials.
→ Creates UsernamePasswordAuthenticationToken.
→ Token sent to AuthenticationManager
→ Manager calls AuthenticationProvider
→ Provider loads user via UserDetailsService
→ Password validated using PasswordEncoder
→ If valid, it returns an authenticated token containing UserDetails and authorities.
→ Spring Security stores this authenticated object in the SecurityContext.

Note:
- Avoid implementing UserDetails directly in your entity class.
- Avoid implementing UserDetailsService directly inside a business service class.
- Use separate dedicated classes to avoid tight coupling.

----------------------------------------------------------------------------------------------------------------------------------------

Security Context:

- Stores all authentication and authorization data.
- Holds the Authentication object for the current request.

Use Cases:
1. Access Current User:
    String currentUser = SecurityContextHolder.getContext().getAuthentication().getName();


2. Check Role:
    if (SecurityContextHolder.getContext().getAuthentication().getAuthorities().contains("ROLE_ADMIN")) {
         // Allow admin action
    }

----------------------------------------------------------------------------------------------------------------------------------------

UsernamePasswordAuthenticationToken Details:

This token carries user credentials.
If created with username and password → user is NOT yet authenticated. The token must be validated by the AuthenticationManager.
If created using UserDetails with password = null and authorities provided → user is considered authenticated.
    Valid when using JWT token

----------------------------------------------------------------------------------------------------------------------------------------