----------------------------------------------------------------------------------------------------------------------------------------
Lecture 1: SPRING SECURITY
----------------------------------------------------------------------------------------------------------------------------------------

1. Authentication:
    - Checks if the user is valid.

2. Authorization:
    - Checks whether the authenticated user has the required roles/permissions to access a resource.

----------------------------------------------------------------------------------------------------------------------------------------

Spring Security Overview:

1. Adding the Spring Security dependency automatically secures all controller APIs.
2. If no username/password is configured, Spring Security generates a random password (UUID) at application startup.
3. When any API is accessed, Spring Security redirects the user to the login page.
4. After successful login, the user is redirected back to the originally requested API.
5. Sessions are stored server-side. Once authenticated through any API, the user can access all other endpoints without re-logging in until the session expires.

----------------------------------------------------------------------------------------------------------------------------------------

Session Management:

- A session is a server-maintained state to track user interactions across multiple requests.
- When a user accesses the application for the first time, the server creates a session.

JSESSIONID:
- A unique session ID generated by the server.
- Sent to the client as a cookie or appended as a URL parameter.
- On later requests, the browser sends back the JSESSIONID so the server can identify the user session.
- The session ends when it expires (default: 30 minutes) or when the user logs out.

Network Tab Insights:
- Username and password appear in the request payload during login.
- Request Headers: JSESSIONID sent to the server.
- Response Headers: JSESSIONID returned by the backend.

Session Timeout:
- Sessions expire after a period of inactivity.
- Timeout duration is configurable in the application.

----------------------------------------------------------------------------------------------------------------------------------------

Spring Security Filter Chain:

- A chain of security filters applied to every incoming HTTP request.
- Placed between the DispatcherServlet and the Controller.

Key Components:

1. UsernamePasswordAuthenticationFilter:
    - Intercepts login requests, extracts username and password, creates an authentication token, Sends the token to the AuthenticationManager.

2. AuthenticationManager:
    - Accepts the authentication token., Delegates credential validation to an AuthenticationProvider.

3. AuthenticationProvider:
    - Performs actual credential validation.
    - Calls UserDetailsService to load user data..
    - Compares the provided password with the stored one using PasswordEncoder.
    - Returns a fully authenticated Authentication object containing user details and authorities.eds.

4. Authentication Object:
    - Contains username, password (usually null after authentication), UserDetails, and roles.

5. UserDetailsService:
    - Interface used by Spring Security to load user data (username, password, roles) from the database.

6. UserDetails:
    - Interface holding user data required for credential validation.

Authentication Flow:
- User submits login form.
-UsernamePasswordAuthenticationFilter extracts credentials.
-Creates UsernamePasswordAuthenticationToken.
-Token goes to AuthenticationManager.
-Manager uses AuthenticationProvider (e.g., DaoAuthenticationProvider).
-Provider loads user via UserDetailsService and verifies the password.
-If valid, it returns an authenticated token containing UserDetails and authorities.
-Spring Security stores this authenticated object in the SecurityContext.

Note:
- Avoid implementing UserDetails directly in your entity class.
- Avoid implementing UserDetailsService directly inside a business service class.
- Use separate dedicated classes to avoid tight coupling.

----------------------------------------------------------------------------------------------------------------------------------------

Security Context:

- Stores all authentication and authorization data.
- Holds the Authentication object for the current request.

Use Cases:
1. Get current username:
    String currentUser = SecurityContextHolder.getContext().getAuthentication().getName();


2. Check if user has admin role
    if (SecurityContextHolder.getContext().getAuthentication().getAuthorities().contains("ROLE_ADMIN")) {
         // Allow admin action
    }

----------------------------------------------------------------------------------------------------------------------------------------

UsernamePasswordAuthenticationToken Details:

This token carries user credentials.
If created with username and password → user is NOT yet authenticated. The token must be validated by the AuthenticationManager.
If created using UserDetails with password = null and authorities provided → user is considered authenticated.

Bypassing Validation

If you create a token using UserDetails and manually set it in the SecurityContext, the user becomes authenticated without password checking.
If you create a token with raw username/password and set it directly in the SecurityContext, the user is still considered unauthenticated because the credentials were never validated.
Only perform manual setting when you are certain the user is already authenticated (e.g., after custom validation logic).

----------------------------------------------------------------------------------------------------------------------------------------