----------------------------------------------------------------------------------------------------------------------------------------
Lecture 1: SPRING SECURITY:
----------------------------------------------------------------------------------------------------------------------------------------

1: Authentication : 
    To check if the user is valid or not

2: Authorization:
    To check if the user has roles/permission to access 

----------------------------------------------------------------------------------------------------------------------------------------

Spring Security:

1: When you use spring security dependency it will automatically give security to all the APIs present in the controller.
2 :If you didnt set the username and password it will generate password on its own when you run the application.
3: Password will be the random UUID.
4: When you hit any API in the application it will redirect you to the login page.
5: Once you give the credentials it will redirect you to original API.
5: The session is of the server not particular APIs means if we login using one API and gave user credentials
   Then I can access any API without going to login page.

----------------------------------------------------------------------------------------------------------------------------------------

Session:
    It is a stateful interaction where server maintains the user information across multiple request.
    When a user access the application for the first time, a session is created from the server.

JSESSIONID:
    JSESSIONID is a unique session ID generated by the server when a user starts a session.
    It helps the server identify and maintain the users session across multiple HTTP requests.

How JSESSIONID Works
    When a client (browser) makes a request to application, the server generates a JSESSIONID.
    This ID is sent to the client in the response either as a cookie or a URL parameter.
    Now, whenever client makes a another request to the application
    the client sends the JSESSIONID to the server, allowing the server to retrieve the stored session data.
    When the session expires (default: 30 minutes) or the user logs out, the session is destroyed.

Network TAB:
    In payload you will see the username and password
    Request Headers = Jsession ID in this is which is sent from the browser.
    Response Headers = Jsession ID in this is which is get from the BE.

Session Timeout:
    Sessions have a timeout period. If there is no activity from the user within a specified time, the session may expire.
    Session timeout can be configured in the application.

----------------------------------------------------------------------------------------------------------------------------------------

SPRING SECURITY FILTER CHAIN:
    It is a series of filters that are applied to incoming HTTP Requests to enforce security policies.
    Ex: Basic Authentication, Authorization etc etc.
    It is placed between the Dispatcher Servlet and Controller.

UsernamePasswordAuthentication Filter :
    This filter intercept the login requests and fetch the username and password and create a authentication token 
    and passes to authentication manager to validate the credentials.

AuthenticationManager:
    It validates the username and password via UserDetailsService
    If it valids it returns valid authentication object otherwise return not valid authentication object.

Authentication Object:
    Object that contains username , password, UserDetails Object and roles

UserDetailsService:
    It is an interface used by spring security to load user data from the DB.

UserDetails:
    It is an interface used by spring security which holds the user data and needed to validate the credentials.

Flow: 
    Authentication managers calls UserDetailsService to load the data
    UserDetailsService loads and return the UserDetails Object
    AuthenticationManager validates the data and set the security context.

Note:
Dont Implement UserDetails in entity class and UserDetailsService in service class 
Make sepearate classes for these implentation so these are not tightly coupled with entity and service classes

----------------------------------------------------------------------------------------------------------------------------------------

Security Context Holder:
    It a storage where security Context is stored.

----------------------------------------------------------------------------------------------------------------------------------------

Security Context:
Its a container that contains user authentication and authorization data
Ex: Authentication object is stored in the security Context

Use Cases : 
1: String currentUser = SecurityContextHolder.getContext().getAuthentication().getName();
2: if (SecurityContextHolder.getContext().getAuthentication().getAuthorities().contains("ROLE_ADMIN")) {
    // Allow admin action
    }

----------------------------------------------------------------------------------------------------------------------------------------



