----------------------------------------------------------------------------------------------------------------------------------------
Lecture 1: SPRING SECURITY
----------------------------------------------------------------------------------------------------------------------------------------

1. Authentication:
    - Verifies if the user is valid.

2. Authorization:
    - Checks if the user has the required roles/permissions to access resources.

----------------------------------------------------------------------------------------------------------------------------------------

Spring Security Overview:

1. Adding the Spring Security dependency automatically secures all APIs in the controller.
2. If username and password are not set, Spring Security generates a random password (UUID) at runtime.
3. On accessing any API, users are redirected to the login page.
4. After successful login, users are redirected to the originally requested API.
5. Sessions are server-based, not API-specific. Once logged in via any API, users can access all APIs without re-authentication.

----------------------------------------------------------------------------------------------------------------------------------------

Session Management:

- A session is a stateful interaction where the server maintains user information across multiple requests.
- When a user accesses the application for the first time, the server creates a session.

JSESSIONID:
- A unique session ID generated by the server when a session starts.
- Sent to the client as a cookie or URL parameter.
- On subsequent requests, the client sends the JSESSIONID, allowing the server to retrieve session data.
- The session is destroyed when it expires (default: 30 minutes) or the user logs out.

Network Tab Insights:
- Username and password are visible in the payload.
- Request Headers: JSESSIONID sent from the browser.
- Response Headers: JSESSIONID received from the backend.

Session Timeout:
- Sessions expire after a period of inactivity.
- Timeout duration is configurable in the application.

----------------------------------------------------------------------------------------------------------------------------------------

Spring Security Filter Chain:

- A series of filters applied to incoming HTTP requests to enforce security policies (e.g., authentication, authorization).
- Positioned between the Dispatcher Servlet and Controller.

Key Components:

1. UsernamePasswordAuthenticationFilter:
    - Intercepts login requests, extracts username and password, creates an authentication token, and passes it to the AuthenticationManager.

2. AuthenticationManager:
    - Validates user credentials by passing the authentication token to the AuthenticationProvider.

3. AuthenticationProvider:
    - Performs actual credential validation.
    - Uses UserDetailsService to load user data from the database.
    - Compares the provided password with the stored password.
    - Returns an authentication object with user details and roles if validation succeeds.

4. Authentication Object:
    - Contains username, password, UserDetails object, and roles.

5. UserDetailsService:
    - Interface used by Spring Security to load user data (username, password, roles) from the database.

6. UserDetails:
    - Interface holding user data required for credential validation.

Authentication Flow:
- User submits credentials via login form.
- UsernamePasswordAuthenticationFilter extracts credentials and creates a UsernamePasswordAuthenticationToken.
- Token is passed to AuthenticationManager for authentication.
- AuthenticationManager delegates to AuthenticationProviders (e.g., DaoAuthenticationProvider).
- DaoAuthenticationProvider extracts credentials, calls UserDetailsService to load user data, and uses PasswordEncoder to verify the password.
- If valid, creates an authenticated UsernamePasswordAuthenticationToken with user details and authorities.
- Authenticated token is stored in the security context.

Note:
- Do NOT implement UserDetails in the entity class or UserDetailsService in the service class.
- Create separate classes for these implementations to avoid tight coupling.

----------------------------------------------------------------------------------------------------------------------------------------

Security Context Holder:

- Storage for the Security Context.

----------------------------------------------------------------------------------------------------------------------------------------

Security Context:

- Container holding user authentication and authorization data (e.g., Authentication object).

Use Cases:
1. Retrieve current username:
    String currentUser = SecurityContextHolder.getContext().getAuthentication().getName();

2. Check for admin role:
    if (SecurityContextHolder.getContext().getAuthentication().getAuthorities().contains("ROLE_ADMIN")) {
         // Allow admin action
    }

----------------------------------------------------------------------------------------------------------------------------------------

UsernamePasswordAuthenticationToken is a token which takes credentials of the user and passed to authentication manager to verify
If username and password is passed means it not verified and needs to verify from authenticationManager
If userDetails, pass = null and roles are passed means user is authenticated and can be directly set to the security context

If you create token using userDetails then you can directly bypass the validation by setting the securityContext
If you create token using username and password and set the security context then you bypassed the validation but the user is still unauthenticated 
so do this only when user is authenticated 

----------------------------------------------------------------------------------------------------------------------------------------