-----------------------------------------------------------------------------------------------------------------------------------------------------
Lecture 1: SPRING SECURITY
-----------------------------------------------------------------------------------------------------------------------------------------------------

1. Authentication:
    → Validates username + password 
    → Validates Token

2. Authorization:
    → Checks roles + authorities after authentication

-----------------------------------------------------------------------------------------------------------------------------------------------------

Spring Security Overview:

1: Spring security automatically secures all the APIs when dependency is added
2: Random password is generated if no username/password is configured
3: Session based authentication is automaticallty applied   
4: Once user is authenticated, it can access all the secured APIs without re-login using session

-----------------------------------------------------------------------------------------------------------------------------------------------------

Session:
    → When a user login, the server creates a session with user details
    → Session ends after expiration time or when user logs out
    → Jsession id is sent to the client and stored in cookies 
    → Client sends jessionID with every request and server uses it to identify the session
    → Need some kind of storage to store sesssion, redis is mostly used
    → Session
        ├── sessionId
        ├── userId
        ├── username
        ├── roles
        ├── authenticated=true
        ├── securityContext
        └── app-specific attributes

JSESSIONID:
    → A unique sessionId generated by the server

-----------------------------------------------------------------------------------------------------------------------------------------------------

Spring Security Filter Chain:
    → A chain of security filters applied to every request
    → Placed between the DispatcherServlet and the Controller.

Key Components:

1. UsernamePasswordAuthenticationFilter:
    → Intercepts login requests         
    → extracts username and password
    → creates an usernamePasswordAuthentication token   
    → Token sent to AuthenticationManager

2. AuthenticationManager:
    → Accepts the authentication token  
    → Delegates credential to AuthenticationProvider

3. AuthenticationProvider:
    → Validates Credentials
    → Returns authenticated Authentication object which contains userDetails and authorities

4. Authentication Object:
    → Contains Principal(UserDetails), Credentials (usually null after auth), Roles.

-----------------------------------------------------------------------------------------------------------------------------------------------------

Security Context:
    → Stores all authentication and authorization data.
    → Holds the Authentication object for the current request.

Use Cases:
1. Access Current User:
    String currentUser = SecurityContextHolder.getContext().getAuthentication().getName();


2. Check Role:
    if (SecurityContextHolder.getContext().getAuthentication().getAuthorities().contains("ROLE_ADMIN")) {
         // Allow admin action
    }

-----------------------------------------------------------------------------------------------------------------------------------------------------
UsernamePasswordAuthenticationToken():
-----------------------------------------------------------------------------------------------------------------------------------------------------

1: Not Yet Authenticated (Login Request):

//Username-password Authentication
//Created with just username and password, no authorities
// At this point → authenticated = false
// AuthenticationManager will validate this

UsernamePasswordAuthenticationToken token = new UsernamePasswordAuthenticationToken(username,password);
Authentication result = authenticationManager.authenticate(token);

-----------------------------------------------------------------------------------------------------------------------------------------------------

2: Already Authenticated (JWT Flow):

// Created with UserDetails + null password + authorities
// Used when JWT token is already validated
// Tells Spring Security → this user is already verified
// At this point → authenticated = true
// Set directly into SecurityContext — no validation needed

UsernamePasswordAuthenticationToken token = new UsernamePasswordAuthenticationToken(userDetails, null, userDetails.getAuthorities());
SecurityContextHolder.getContext().setAuthentication(token);

-----------------------------------------------------------------------------------------------------------------------------------------------------
