-----------------------------------------------------------------------------------------------------------------------------------------------------
Lecture 1: SPRING SECURITY
-----------------------------------------------------------------------------------------------------------------------------------------------------

1. Authentication:
    - Validates username/password or token

2. Authorization:
    - Checks roles/authorities after authentication

-----------------------------------------------------------------------------------------------------------------------------------------------------

Spring Security Overview:

1: Spring security automatically secures all the APIs when dependency is added
2: Random password is generated if no username/password is configured
3: Session is stored in server after login
4: Once user is authenticated, it can access all the secured APIs without re-login using session

-----------------------------------------------------------------------------------------------------------------------------------------------------

Session:
    → When a user login, the server creates a session with user details
    → Session ends after expiration or when user logs out
    → Session
        ├── sessionId
        ├── userId
        ├── username
        ├── roles
        ├── authenticated=true
        ├── securityContext
        └── app-specific attributes

JSESSIONID:
    → A unique sessionId generated by the server
    → Used to identify the session 

-----------------------------------------------------------------------------------------------------------------------------------------------------

Spring Security Filter Chain:
    → A chain of security filters applied to every request
    → Placed between the DispatcherServlet and the Controller.

Key Components:

1. UsernamePasswordAuthenticationFilter:
    → Intercepts login requests         
    → extracts username and password
    → creates an usernamePasswordAuthentication token   
    → Token sent to AuthenticationManager

2. AuthenticationManager:
    → Accepts the authentication token  
    → Delegates credential to AuthenticationProvider

3. AuthenticationProvider:
    → Validates Credentials
    → Returns authenticated Authentication object which contains userDetails and authorities

4. Authentication Object:
    → Contains Principal(UserDetails), Credentials (usually null after auth), Roles.

-----------------------------------------------------------------------------------------------------------------------------------------------------

Security Context:
    → Stores all authentication and authorization data.
    → Holds the Authentication object for the current request.

Use Cases:
1. Access Current User:
    String currentUser = SecurityContextHolder.getContext().getAuthentication().getName();


2. Check Role:
    if (SecurityContextHolder.getContext().getAuthentication().getAuthorities().contains("ROLE_ADMIN")) {
         // Allow admin action
    }

-----------------------------------------------------------------------------------------------------------------------------------------------------

UsernamePasswordAuthenticationToken Details:

→ This token carries user credentials.
→ If created with username and password → user is NOT yet authenticated. The token must be validated by the AuthenticationManager.
→ If created using UserDetails with password = null and authorities provided → user is considered authenticated.
    → Valid when using JWT token

-----------------------------------------------------------------------------------------------------------------------------------------------------